import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from src.config.settings import settings
from src.config.companies import COMPANY_SLUGS
from src.config.constants import PLATFORM_ICONS
from src.utils.logger import get_logger

log = get_logger(__name__)

def send_email(jobs: list[dict]):
    """Send formatted HTML email with job listings."""
    if not jobs:
        return

    primary = [j for j in jobs if j["match_type"] == "primary"]
    bonus = [j for j in jobs if j["match_type"] == "bonus"]

    html = [
        "<html><body>",
        f"<h2>🚀 {len(jobs)} New Data Engineer Job(s) Found</h2>",
        f"<p style='color:#666;'>Filtered ≤ {settings.MAX_EXPERIENCE_YEARS} yrs exp | {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
        f"{len(primary)} primary + {len(bonus)} bonus matches</p>",
        "<hr>",
    ]

    for i, job in enumerate(primary + bonus, 1):
        icon = PLATFORM_ICONS.get(job["platform"], "📋")
        exp_text = f"{job['experience']} yrs" if job["experience"] else "Not specified (likely entry-level)"
        badge = "🎯 Primary" if job["match_type"] == "primary" else "💡 Bonus"
        border_color = "#1a73e8" if job["match_type"] == "primary" else "#f59e0b"

        html.append(f"""
        <div style="margin-bottom:16px; padding:14px; border-left:4px solid {border_color};
                    background:#fafafa; border-radius:4px;">
            <div style="display:flex; justify-content:space-between; align-items:center;">
                <h3 style="margin:0; font-size:16px;">#{i} — {job['title']}</h3>
                <span style="font-size:12px; padding:2px 8px; border-radius:12px;
                       background:{'#e3f2fd' if job['match_type'] == 'primary' else '#fff8e1'};">{badge}</span>
            </div>
            <p style="color:#555; margin:4px 0; font-size:14px;">
                {icon} {job['platform'].title()} · <b>{job['company']}</b> · 📍 {job['location']}
            </p>
            <p style="color:#777; margin:4px 0; font-size:13px;">📋 Experience: {exp_text}</p>
            {'<p style="color:#777; margin:4px 0; font-size:13px;">📅 Posted: ' + job['posted_at'][:10] + '</p>' if job.get('posted_at') else ''}
            <a href="{job['url']}" style="color:#1a73e8; font-weight:bold; font-size:14px;">
                👉 Apply Here
            </a>
        </div>
        """)

    # Stats footer
    platforms_hit = set(j["platform"] for j in jobs)
    html.append(f"""
    <hr>
    <p style="color:#999; font-size:12px;">
        Scanned {sum(len(v) for v in COMPANY_SLUGS.values())} companies across
        {', '.join(platforms_hit)} |
        {len(primary)} primary + {len(bonus)} bonus matches |
        Generated by Job Alert v2
    </p>
    </body></html>
    """)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🔔 {len(jobs)} New Data Engineer Jobs — {datetime.now().strftime('%b %d, %I:%M %p')}"
    msg["From"] = settings.SENDER_EMAIL
    msg["To"] = ", ".join(settings.RECIPIENT_EMAILS)
    msg.attach(MIMEText("\n".join(html), "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SENDER_EMAIL, settings.SENDER_PASSWORD)
            server.sendmail(settings.SENDER_EMAIL, settings.RECIPIENT_EMAILS, msg.as_string())
        log.info(f"✅ Email sent: {len(primary)} primary + {len(bonus)} bonus matches")
    except Exception as e:
        import traceback
        log.error(f"❌ Email failed: {e}")
        log.error(traceback.format_exc())
