import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import re
import requests
from src.config.settings import settings
from src.config.companies import COMPANY_SLUGS
from src.config.constants import PLATFORM_ICONS
from src.config.sponsors import H1B_SPONSORS
from src.utils.logger import get_logger

log = get_logger(__name__)

def _normalize_company(name: str) -> str:
    if not isinstance(name, str):
        return ""
    name = str(name).lower()
    name = re.sub(r'\b(inc\.?|llc|group|corp\.?|corporation|ltd\.?|limited|co\.?|company|services|holdings)\b', '', name)
    return re.sub(r'[^a-z0-9]', '', name)

def send_email(jobs: list[dict]):
    """Send formatted HTML email with job listings."""
    if not jobs:
        return

    primary = [j for j in jobs if j["match_type"] == "primary"]
    bonus = [j for j in jobs if j["match_type"] == "bonus"]

    html = [
        "<html><body>",
        f"<h2>🚀 {len(jobs)} New Job(s) Found</h2>",
        f"<p style='color:#666;'>Filtered ≤ {settings.MAX_EXPERIENCE_YEARS} yrs exp | {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
        f"{len(primary)} primary + {len(bonus)} bonus matches</p>",
        "<hr>",
    ]

    for i, job in enumerate(primary + bonus, 1):
        icon = PLATFORM_ICONS.get(job["platform"], "📋")
        exp_text = f"{job['experience']} yrs" if job["experience"] else "Not specified"
        exp_level = job.get("exp_level", "❓ Not Specified")
        exp_level_colors = {
            "🎓 New Grad": ("#e8f5e9", "#2e7d32"),
            "📗 0-1 YoE": ("#e8f5e9", "#2e7d32"),
            "📘 1-2 YoE": ("#e3f2fd", "#1565c0"),
            "🔶 3+ YoE": ("#fff3e0", "#e65100"),
            "❓ Not Specified": ("#f5f5f5", "#616161"),
        }
        exp_bg, exp_fg = exp_level_colors.get(exp_level, ("#f5f5f5", "#616161"))
        badge = "🎯 Primary" if job["match_type"] == "primary" else "💡 Bonus"
        border_color = "#1a73e8" if job["match_type"] == "primary" else "#f59e0b"

        is_sponsor = _normalize_company(job['company']) in H1B_SPONSORS
        sponsor_html = f'<span style="font-size:12px; padding:2px 8px; border-radius:12px; background:#e8f5e9; color:#2e7d32; margin-left:8px;">🛂 H1B Sponsor</span>' if is_sponsor else f'<span style="font-size:12px; padding:2px 8px; border-radius:12px; background:#ffebee; color:#c62828; margin-left:8px;">Not Sponsored/NOT Sure</span>'

        html.append(f"""
        <div style="margin-bottom:16px; padding:14px; border-left:4px solid {border_color};
                    background:#fafafa; border-radius:4px;">
            <div style="display:flex; justify-content:space-between; align-items:center;">
                <h3 style="margin:0; font-size:16px;">#{i} — {job['title']}</h3>
                <div>
                    <span style="font-size:12px; padding:2px 8px; border-radius:12px;
                           background:{'#e3f2fd' if job['match_type'] == 'primary' else '#fff8e1'};">{badge}</span>{sponsor_html}
                </div>
            </div>
            <p style="color:#555; margin:4px 0; font-size:14px;">
                {icon} {job['platform'].title()} · <b>{job['company']}</b> · 📍 {job['location']}
            </p>
            <p style="color:#777; margin:4px 0; font-size:13px;">📋 Experience: {exp_text} <span style="font-size:11px; padding:2px 6px; border-radius:10px; background:{exp_bg}; color:{exp_fg}; margin-left:6px;">{exp_level}</span></p>
            {'<p style="color:#777; margin:4px 0; font-size:13px;">📅 Posted: ' + job['posted_at'][:10] + '</p>' if job.get('posted_at') else ''}
            <a href="{job['url']}" style="color:#1a73e8; font-weight:bold; font-size:14px;">
                👉 Apply Here
            </a>
        </div>
        """)

    # Stats footer
    platforms_hit = set(j["platform"] for j in jobs)
    html.append(f"""
    <hr>
    <p style="color:#999; font-size:12px;">
        Scanned {sum(len(v) for v in COMPANY_SLUGS.values())} companies across
        {', '.join(platforms_hit)} |
        {len(primary)} primary + {len(bonus)} bonus matches |
        Generated by Job Alert v2
    </p>
    </body></html>
    """)

    subject = f"🔔 {len(jobs)} New Jobs (JOB-AGGREGATOR) — {datetime.now().strftime('%b %d, %I:%M %p')}"
    html_body = "\n".join(html)

    if settings.EMAIL_BACKEND == "resend":
        _send_via_resend(subject, html_body, primary, bonus)
    else:
        _send_via_smtp(subject, html_body, primary, bonus)


def _send_via_smtp(subject: str, html_body: str, primary: list, bonus: list):
    """Send email via Gmail SMTP (port 465). Works locally and on GitHub Actions."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.SENDER_EMAIL
    msg["To"] = ", ".join(settings.RECIPIENT_EMAILS)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(settings.SENDER_EMAIL, settings.SENDER_PASSWORD)
            server.sendmail(settings.SENDER_EMAIL, settings.RECIPIENT_EMAILS, msg.as_string())
        log.info(f"✅ Email sent (SMTP): {len(primary)} primary + {len(bonus)} bonus matches")
    except Exception as e:
        import traceback
        log.error(f"❌ Email failed (SMTP): {e}")
        log.error(traceback.format_exc())


def _send_via_resend(subject: str, html_body: str, primary: list, bonus: list):
    """Send email via Resend REST API (port 443). Works on DigitalOcean."""
    try:
        resp = requests.post(
            "https://api.resend.com/emails",
            headers={
                "Authorization": f"Bearer {settings.RESEND_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "from": settings.SENDER_EMAIL,
                "to": settings.RECIPIENT_EMAILS,
                "subject": subject,
                "html": html_body,
            },
            timeout=15,
        )
        if resp.status_code in (200, 201):
            log.info(f"✅ Email sent (Resend): {len(primary)} primary + {len(bonus)} bonus matches")
        else:
            log.error(f"❌ Email failed (Resend): {resp.status_code} — {resp.text}")
    except Exception as e:
        import traceback
        log.error(f"❌ Email failed (Resend): {e}")
        log.error(traceback.format_exc())
