# Filtered company slugs for OPT STEM / entry-level SWE, DE, AI roles
# Criteria: H1B-sponsoring companies, MAANG/FAANG, Fortune 500 tech, top YC startups
# Removed: local businesses, clinics, law firms, food chains, niche B2C, etc.

COMPANY_SLUGS = {
    "greenhouse": [
        # ── Big Tech / MAANG ──────────────────────────────────────
        "airbnb",
        "anthropic",
        "databricks",
        "datadog",
        "discord",
        "dropbox",
        "duolingo",
        "figma",
        "github",
        "gitlab",
        "gusto",
        "hashicorp",
        "hubspot",
        "instacart",
        "lyft",
        "mongodb",
        "notion",
        "okta",
        "openai",
        "pagerduty",
        "palantir",
        "pinterest",
        "plaid",
        "reddit",
        "rippling",
        "roblox",
        "roku",
        "samsara",
        "scaleai",
        "snowflake",
        "sourcegraph",
        "spotify",
        "squarespace",
        "stripe",
        "toast",
        "twilio",
        "waymo",
        "workday",
        "zscaler",
        "zoominfo",
        # ── Strong YC / VC-backed Startups (OPT-friendly) ─────────
        "abnormalsecurity",
        "acryldata",
        "airbyte",
        "amplitude",
        "anaplan",
        "anduril",
        "andurilindustries",
        "apollographql",
        "assemblyai",
        "axonius",
        "benchling",
        "billcom",
        "braze",
        "brex",
        "carta",
        "celonis",
        "checkr",
        "clickhouse",
        "clickup",
        "cockroachlabs",
        "cofertility",
        "coherehealth",
        "collibra",
        "confluent",
        "contentful",
        "coreweave",
        "cribl",
        "dbtlabsinc",
        "deepmind",
        "domaintools",
        "domo",
        "doordash",
        "elastic",
        "fivetran",
        "fullstory",
        "gong",
        "grafanalabs",
        "grammarly",
        "heap",
        "hightouch",
        "honeycomb",
        "instabase",
        "iterable",
        "klaviyo",
        "launchdarkly",
        "lightricks",
        "liveramp",
        "looker",
        "loom",
        "marqeta",
        "mattermost",
        "mixpanel",
        "moveworks",
        "mural",
        "natera",
        "netlify",
        "newrelic",
        "nextdoor",
        "nextroll",
        "notionlabs",
        "observeai",
        "offerfit",
        "onsiteiq",
        "openai",
        "opendoor",
        "outreach",
        "pandadoc",
        "perplexityai",
        "postman",
        "productboard",
        "ramp",
        "recharge",
        "render",
        "retool",
        "revenuecat",
        "rubrik",
        "runwayml",
        "samsara",
        "securityscorecard",
        "segment",
        "sendbird",
        "sentry",
        "sigmacomputing",
        "singlestore",
        "sisense",
        "smartsheet",
        "snyk",
        "sprinklr",
        "sproutsocial",
        "stackadapt",
        "starburst",
        "supabase",
        "superblocks",
        "tableau",
        "tailscale",
        "temporal",
        "thetradedesk",
        "timescale",
        "togetherai",
        "typeform",
        "vanta",
        "vimeo",
        "voltrondata",
        "webflow",
        "whatnot",
        "yugabyte",
        "zapier",
        "zilliz",
        # ── Discovered 2026-03-16 ──────────────────────────────────
        "appian",              # Appian — low-code automation platform
        "appliedintuition",    # Applied Intuition — AI autonomous vehicles
        "axon",                # Axon — AI public safety tech
        "c3iot",               # C3.ai — enterprise AI  (slug: c3iot, not c3ai)
        "canonical",           # Canonical — Linux/Ubuntu/cloud infrastructure
        "cloudflare",          # Cloudflare — network security & infrastructure
        "figureai",            # Figure AI — AI humanoid robotics
        "fireworksai",         # Fireworks AI — LLM inference platform
        "flexport",            # Flexport — logistics & supply chain tech
        "gleanwork",           # Glean — AI enterprise search  (slug: gleanwork)
        "humeai",              # Hume AI — emotional AI / voice
        "imc",                 # IMC Trading — quant trading (strong SWE pipeline)
        "janestreet",          # Jane Street — quant trading (SWE/DE roles)
        "lucidmotors",         # Lucid Motors — EV tech, strong software division
        "robinhood",           # Robinhood Markets — fintech / retail investing
        "twitch",              # Twitch (Amazon) — streaming / gaming infrastructure
        "verkada",             # Verkada — physical security cloud platform
        "warp",                # Warp — AI-native terminal (dev tools)
        "wehrtyou",            # Hudson River Trading — quant trading  (slug: wehrtyou)
    ],

    "lever": [
        # ── Big Tech / Strong OPT-friendly ───────────────────────
        "anyscale",
        "benchling",
        "carta",
        "cerebras-systems",
        "chainalysis",
        "cloudinary",
        "coinbase",
        "contentsquare",
        "copyai",
        "dbt-labs",
        "deepjudge",
        "deel",
        "dronedeploy",
        "earnin",
        "epoch-ai",
        "faire",
        "figma-2",
        "fivetran",
        "floqast",
        "foursquare",
        "fullscript",
        "gearset",
        "gopuff",
        "grammarly",
        "greenlight",
        "h1",
        "highspot",
        "hive",
        "ironclad",
        "iterable",
        "iterative",
        "jumpcloud",
        "labelbox",
        "lemonade",
        "linear",
        "livechatinc",
        "lucid",
        "lucidworks",
        "masterclass",
        "matchgroup",
        "mercury",
        "metabase",
        "mistral",
        "mixpanel",
        "modern",
        "moonpay",
        "mux",
        "netflix",
        "netlify",
        "noom",
        "o-p-e-n",
        "palantir",
        "plaid",
        "postman",
        "prefect",
        "quantcast",
        "quizlet-2",
        "rackspace",
        "rainforest",
        "regalvoice",
        "replit",
        "restaurant365",
        "retool",
        "rigetti",
        "ro",
        "runway",
        "safetyculture-2",
        "sanabenefits",
        "saviynt",
        "sensorto",
        "sensortower",
        "sigma-computing",
        "siteground",
        "smartbugoperatingllc",
        "sonarsource",
        "spotify",
        "sprinterhealth",
        "sysdig",
        "tala",
        "teachable",
        "teleport",
        "temporal-technologies",
        "trendyol",
        "trustarc",
        "trustly",
        "twodots",
        "udemy",
        "veeva",
        "verygoodsecurity",
        "vevo",
        "voleon",
        "vouch",
        "waabi",
        "walkme",
        "wayground",
        "wealthfront",
        "wealthsimple",
        "webflow",
        "webfx",
        "whoop",
        "wiz-inc",
        "workos",
        "xpansiv",
        "zapier",
        "zilliz",
        "zimperium",
        # ── Discovered 2026-03-16 ──────────────────────────────────
        "atlassian",           # Atlassian — developer tools (Jira, Confluence)
        "canva",               # Canva — design platform (H1B: canvaus)
    ],

    "ashby": [
        # ── Top OPT-friendly startups on Ashby ───────────────────
        "1password",
        "abridge",
        "acorns",
        "adaptive",
        "airwallex",
        "aleph",
        "allspice",
        "altimate",
        "ambiencehealthcare",
        "ambrook",
        "anrok",
        "anyscale",
        "anything",
        "apollo-graphql",
        "assembledhq",
        "astronomer",
        "atlan",
        "atob",
        "atomic-financial",
        "attio",
        "auditboard",
        "aurorasolar",
        "automat",
        "axionray",
        "backmarket",
        "basis-ai",
        "betterup",
        "bland",
        "blockdaemon",
        "blockworks",
        "bubble",
        "browserbase",
        "camunda",
        "candidhealth",
        "capchase",
        "captions",
        "cartesia",
        "chainalysis-careers",
        "chainlink-labs",
        "chattermill",
        "chronospherejobs",
        "clarisights",
        "clearbank",
        "clerk",
        "close",
        "codat",
        "codegen",
        "coder",
        "coderabbit",
        "cognition",
        "cohere",
        "cointracker",
        "commonroom",
        "confluent",
        "conductorone",
        "convex-dev",
        "cradlebio",
        "crusoe",
        "cyberhaven",
        "d-matrix",
        "dandy",
        "datacurve",
        "datatonic",
        "decagon",
        "deel",
        "deepgram",
        "deepl",
        "delinea",
        "deliveroo",
        "directive",
        "dittoai",
        "docker",
        "doppel",
        "dune",
        "dust",
        "e2b",
        "eigen-labs",
        "eightsleep",
        "elevenlabs",
        "elicit",
        "eliseai",
        "ellipsislabs",
        "envoy",
        "etched",
        "elevenlabs",
        "evenup",
        "fal-ai",
        "fieldguide",
        "finalroundai",
        "flatfile",
        "fluidstack",
        "fonoa",
        "found",
        "foxglove",
        "freeplay",
        "freshpaint",
        "g2",
        "gecko-robotics",
        "gitbook",
        "gitpod",
        "goodstack",
        "gorgias",
        "gptzero",
        "gradient-labs",
        "grafbase",
        "granica",
        "granola",
        "graphite",
        "griffin",
        "hackerone",
        "harbor",
        "harmonic",
        "harvey",
        "heliux",
        "higharc",
        "hopper",
        "horizon3ai",
        "human",
        "illumio",
        "imprint",
        "incident",
        "indent",
        "inngest",
        "inscribeai",
        "inworld-ai",
        "ironcladhq",
        "kayak",
        "kintsugi",
        "klarity",
        "klue",
        "knoetic",
        "kodex",
        "kojo",
        "kong",
        "kustomer",
        "lambda",
        "lancedb",
        "langchain",
        "langfuse",
        "ledger",
        "leland",
        "lemlist",
        "lendable",
        "levelpath",
        "lightspark",
        "lilt",
        "lime",
        "limitless",
        "linear",
        "livekit",
        "lorikeet",
        "luminai",
        "luminovo",
        "luxor",
        "lynk",
        "lyric",
        "machinify",
        "madhive",
        "magiceden",
        "mapbox",
        "mazedesign",
        "mazehq",
        "mem0",
        "menlosecurity",
        "mercor",
        "meridianlink",
        "metaview",
        "meticulous",
        "middesk",
        "modal",
        "modernfi",
        "mollie",
        "monarchmoney",
        "mondoo",
        "montecarlodata",
        "moonshot-ai",
        "moonvalley-ai",
        "motherduck",
        "mubi",
        "mui",
        "multiverse",
        "mural",
        "mux",
        "n8n",
        "neon",
        "nerdwallet",
        "netboxlabs",
        "newfront",
        "nirvana",
        "nomic",
        "norm-ai",
        "notion",
        "novo",
        "numeral",
        "numeric",
        "nuna",
        "nuon",
        "nylas",
        "observeinc",
        "opengov",
        "openphilanthropy",
        "openrouter",
        "opensea",
        "oplabs",
        "opslevel",
        "orb",
        "orca",
        "orchard",
        "oso",
        "outliant",
        "overjet",
        "oyster",
        "paddle",
        "panoptyc",
        "parabola-io",
        "paradigm",
        "parafin",
        "paragon",
        "patlytics",
        "patreon",
        "pearlhealth",
        "permitflow",
        "phil",
        "photoroom",
        "pinecone",
        "posthog",
        "prepared911",
        "primeintellect",
        "prior-labs",
        "prisma",
        "prokeep",
        "proofofplay",
        "provable",
        "pylon",
        "pylon-labs",
        "qawolf",
        "qdrant",
        "qualified",
        "quora",
        "quicknode",
        "radar",
        "ramp",
        "readme",
        "realfast",
        "realitydefender",
        "recraft",
        "reframesystems",
        "relayfi",
        "relevanceai",
        "remedyrobotics",
        "render",
        "replicant",
        "replit",
        "rerun",
        "rescale",
        "resend",
        "retool",
        "rho",
        "roboflow",
        "rogo",
        "runway",
        "rutter",
        "salient",
        "sanity",
        "sardine",
        "scale-ai",
        "scribd",
        "secfix",
        "semperis",
        "sentient",
        "sentry",
        "serverobotics",
        "sfcompute",
        "sierra",
        "signal-ai",
        "signalfire",
        "signoz",
        "silver",
        "siro",
        "skymavis",
        "snowflake",
        "snyk",
        "socket",
        "socure",
        "sona",
        "sourcegraph",
        "span",
        "speak",
        "speckle",
        "sprig",
        "supabase",
        "suno",
        "superduper",
        "superpower",
        "sweep",
        "sybill-ai",
        "symbiotic",
        "synthflow",
        "tabs",
        "taktile",
        "tandem",
        "tandem-health",
        "tavus",
        "tennr",
        "the-global-talent-co",
        "tinybird",
        "together-ai",
        "tonal",
        "top-hat",
        "topline-pro",
        "traba",
        "trigger-dev",
        "turso",
        "twelve-labs",
        "uipath",
        "unify",
        "unit",
        "unlearn",
        "upstash",
        "vanta",
        "vapi",
        "vendelux",
        "vercel",
        "vetcove",
        "visanahealth",
        "vizcom",
        "vooma",
        "vow",
        "watershed",
        "weave",
        "webai",
        "windmill",
        "wispr-flow",
        "withclutch",
        "withpulley",
        "worldly",
        "wrapbook",
        "writer",
        "wynd-labs",
        "xlabs",
        "ycombinator",
        "zapier",
        "zauber",
        "zed",
        "zip",
        # ── Discovered 2026-03-16 ──────────────────────────────────
        "allium",              # Allium — blockchain data analytics
        "continue",            # Continue.dev — OSS AI code assistant
        "eventualcomputing",   # Eventual Computing — distributed systems / Rust
        "genmo",               # Genmo — AI video generation
        "gigaml",              # Giga AI — AI training infrastructure
        "n1",                  # N1 — AI data platform
        "persona",             # Persona — identity verification / fraud (Series C)
        "sentilink",           # SentiLink — synthetic fraud detection / fintech
        "sentra",              # Sentra — cloud data security
        "uncountable",         # Uncountable — AI R&D platform (chemistry / materials)
    ],

    "workable": [
        # ── Relevant ones from original (already small list) ──────
        "contentful",
        "deepl",
        "n26",
        "pitch",
        "typeform",
    ],

    # ── Oracle Cloud HCM (Fortune 500 / large tech) ──────────────
    "oraclecloud": [
        {"name": "jpmorgan", "domain": "jpmc.fa.oraclecloud.com", "site": "CX_1001"},
        {"name": "goldman_sachs", "subdomain": "hdpc", "region": "us2", "site": "CX_1"},
        {"name": "bny_mellon", "subdomain": "eofe", "region": "us2", "site": "CX_1001"},
        {"name": "american_express", "domain": "egug-dev1.fa.us2.oraclecloud.com", "site": "CX_4001"},
        {"name": "oracle", "subdomain": "eeho", "region": "us2", "site": "CX_1"},
        {"name": "fortinet", "subdomain": "edel", "region": "us2", "site": "CX_2001"},
        {"name": "honeywell", "domain": "ibqbjb.fa.ocs.oraclecloud.com", "site": "Honeywell"},
        {"name": "ford", "subdomain": "efds", "region": "em5", "site": "CX_1"},
    ],

    # ── Workday (Fortune 500 / MAANG-tier) ───────────────────────
    "workday": [
        {"name": "netflix", "instance": "netflix.wd1", "site": "Netflix"},
        {"name": "nvidia", "instance": "nvidia.wd5", "site": "NVIDIAExternalCareerSite"},
        {"name": "salesforce", "instance": "salesforce.wd12", "site": "External_Career_Site"},
        {"name": "salesforce_intern", "instance": "salesforce.wd12", "site": "Futureforce_Internships"},
        {"name": "adobe", "instance": "adobe.wd5", "site": "external_experienced"},
        {"name": "broadcom", "instance": "broadcom.wd1", "site": "External_Career"},
        {"name": "intel", "instance": "intel.wd1", "site": "External"},
        {"name": "dell", "instance": "dell.wd1", "site": "External"},
        {"name": "snap", "instance": "snapchat.wd1", "site": "snap"},
        {"name": "zillow", "instance": "zillow.wd5", "site": "Zillow_Group_External"},
        {"name": "autodesk", "instance": "autodesk.wd1", "site": "Ext"},
        {"name": "workday_co", "instance": "workday.wd5", "site": "Workday"},
        {"name": "workiva", "instance": "workiva.wd503", "site": "careers"},
        {"name": "crowdstrike", "instance": "crowdstrike.wd5", "site": "crowdstrikecareers"},
        {"name": "capital_one", "instance": "capitalone.wd12", "site": "Capital_One"},
        {"name": "visa", "instance": "visa.wd5", "site": "Visa"},
        {"name": "paypal", "instance": "paypal.wd1", "site": "jobs"},
        {"name": "mastercard", "instance": "mastercard.wd1", "site": "CorporateCareers"},
        {"name": "transunion", "instance": "transunion.wd5", "site": "TransUnion"},
        {"name": "pnc", "instance": "pnc.wd5", "site": "External"},
        {"name": "lseg", "instance": "lseg.wd3", "site": "Careers"},
        {"name": "wex", "instance": "wexinc.wd5", "site": "WEXInc"},
        {"name": "accenture", "instance": "accenture.wd103", "site": "AccentureCareers"},
        {"name": "pwc", "instance": "pwc.wd3", "site": "US_Experienced_Careers"},
        {"name": "jll", "instance": "jll.wd1", "site": "jllcareers"},
        {"name": "walmart", "instance": "walmart.wd5", "site": "WalmartExternal"},
        {"name": "target", "instance": "target.wd5", "site": "targetcareers"},
        {"name": "draftkings", "instance": "draftkings.wd1", "site": "DraftKings"},
        {"name": "fox", "instance": "fox.wd1", "site": "Domestic"},
        {"name": "bms", "instance": "bristolmyerssquibb.wd5", "site": "BMS"},
        {"name": "danaher", "instance": "danaher.wd1", "site": "DanaherJobs"},
        {"name": "travelers", "instance": "travelers.wd5", "site": "External"},
        # ── Discovered 2026-03-16 ──────────────────────────────────
        {"name": "cisco",        "instance": "cisco.wd5",         "site": "Cisco_Careers"},
        {"name": "ebay",         "instance": "ebay.wd5",          "site": "apply"},
        {"name": "expedia",      "instance": "expedia.wd108",     "site": "search"},
        {"name": "factset",      "instance": "factset.wd108",     "site": "FactSetCareers"},
        {"name": "micron",       "instance": "micron.wd1",        "site": "External"},
        {"name": "morningstar",  "instance": "morningstar.wd5",   "site": "Americas"},
        {"name": "qualcomm",     "instance": "qualcomm.wd12",     "site": "External"},
        {"name": "redhat",       "instance": "redhat.wd5",        "site": "Jobs"},
        {"name": "servicetitan", "instance": "servicetitan.wd1",  "site": "ServiceTitan"},
        {"name": "spglobal",     "instance": "spgi.wd5",          "site": "SPGI_Careers"},
        {"name": "zoom",         "instance": "zoom.wd5",          "site": "Zoom"},
        # ── Discovered 2026-03-16 (follow-up verification) ────────
        {"name": "blackrock",    "instance": "blackrock.wd1",     "site": "BlackRock_Professional"},
        {"name": "etsy",         "instance": "etsy.wd5",          "site": "Etsy_Careers"},
    ],
}
